MCU = atmega32u4
BOOTLOADER = atmel-dfu
# BOOTLOADER = caterina

RGBLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = lite


MOUSEKEY_ENABLE     = no
PIMORONI_TRACKBALL_ENABLE = no


WPM_ENABLE = no
MODULAR_BONGOCAT_ENABLE = no
QMK_LOGO_ENABLE = no
KYRIA_LOGO_ENABLE = no
