MCU = atmega32u4
BOOTLOADER = atmel-dfu
# BOOTLOADER = caterina

RGBLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = no


MOUSEKEY_ENABLE     = no
PIMORONI_TRACKBALL_ENABLE = no


WPM_ENABLE = no
MODULAR_BONGOCAT_ENABLE = no
QMK_LOGO_ENABLE = no
KYRIA_LOGO_ENABLE = no


COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
